# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gwfa_c <- function(pt_x, pt_y, coord_x, coord_y, bandwith, taille_sample, rayons, qs) {
    .Call('gwfa_gwfa_c', PACKAGE = 'gwfa', pt_x, pt_y, coord_x, coord_y, bandwith, taille_sample, rayons, qs)
}

